baseURL: http://cloudac7.github.io
languageCode: en-us
title: "Koisuru Asteroid"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
#googleAnalytics: <your google analytics id>

# Enable Disqus forum
# optional
#disqusShortname: <your disqus short code>

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  gitRepo: https://github.com/cloudac7/cloudac7.github.io

  darkMode:
    provider: darkreader
    enable: true
    default: system
  
  features:
    # Enable and configure blog posts
    blog:
      enable: true
      shareButtons:
        twitter: true
        reddit: true
        email: true
    comment:
      enable: true
      disqus:
        shortName: cloudac7-github-io
  
  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Show tags under the post title
  enableTags: true

  # Specify whether to show flag in the language selector. Default is true.
  showFlags: true