name: Deploy to Github Pages

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境为最新版 Ubuntu
    name: auto deploy
    steps:
    # 1. 获取源码
    - name: Checkout
      uses: actions/checkout@v3 # 使用 actions/checkout@v3
      with: # 条件
        submodules: true # Checkout private submodules(themes or something else). 当有子模块时切换分支？
    # 2. 配置环境
    - name: Setup Node.js environment
      uses: actions/setup-node@master
      with:
        node-version: "22.x" # 指定 Node.js 版本为 22.x
    # 3. 替换Markdown中的图片位置，将 `source/images` 替换为 `/images`
    - name: Replace image paths in Markdown files
      run: |
        find . -name "*.md" -type f -exec sed -i 's/source\/images/\/images/g' {} \;
    # 4. 生成静态文件
    - name: Generate Public Files
      run: |
        npm i
        npm install hexo-cli -g
        hexo clean && hexo generate
    # 5. 部署到 GitHub 仓库
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: public
        clean: true
        single-commit: true